Repository streamnative/mop, pull requests merged in 2022-04, with the labels that each got.

#572 Close MoP resource when protocol handler close.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTConnectionManager.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
Labels: no-need-doc

#575 Support proxy side dynamic subscribe new topic by the filter.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MqttPropertyUtils.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/properties/PulsarProperties.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/properties/package-info.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarEventCenterImpl.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ProxyIntegrationTest.java
Labels: proxy, no-need-doc

#580 Fix NPE caused by the connection doesn't init complete then invoke close.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
Labels: release/2.9.2, release/2.10.0, no-need-doc

#582 Change ``connection`` close logic to fix some potential probelms.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTConnectionManager.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/TopicSubscriptionManager.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ReasonCodeOnAllACKTest.java
Labels: no-need-doc

#583 Provide separate TLS parameters for MoP
  README.md
  docs/mop-configuration.md
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTChannelInitializer.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyChannelInitializer.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/broker/ConfigurationCompatibilityTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/TLSTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTLSTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
Labels: doc-added

#587 Fix wrong servlet path in test
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
Labels: no-need-doc

#585 Deprecate TLS rely on Pulsar `tlsEnabled` configuration.
  README.md
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/TLSTest.java
Labels: doc

#586 Support Proxy `PulsarClient` connect to Broker with TLS
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/ConfigurationUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyToPulsarTlsTest.java
Labels: no-need-doc

#593 Use compatible `MessageAckBuilder` to instead of `AckHandler`
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonInboundHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/AdapterChannel.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/CombineHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MqttAdapterDecoder.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MqttAdapterEncoder.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MqttAdapterMessage.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MqttPropertyUtils.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/DisconnectAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttConnectAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttDisconnectAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttPubAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttSubAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttUnsubAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/SubscribeAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/UnsubscribeAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/codes/mqtt3/Mqtt3ConnReasonCode.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/codes/mqtt5/Mqtt5ConnReasonCode.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttDisconnectAckMessageHelper.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttPubAckMessageHelper.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttUnsubAckMessageHelper.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/package-info.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/AbstractCommonProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/WillMessageHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AbstractAckHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AckHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AckHandlerFactory.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/MqttV3xAckHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/MqttV5AckHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/package-info.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/ChannelFutureUtils.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
Labels: no-need-doc

#594 Fix send message to consumer not release buf bug.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MqttAdapterEncoder.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MqttAdapterMessage.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/FutureUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTLSTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
  tests/src/test/resources/log4j2.xml
Labels: no-need-doc

#598 Add maxPendingSendRequest to limit client side sending rate.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/AdapterChannel.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MqttAdapterMessage.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
Labels: doc-required

#600 Support proxy connection pool
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/AdapterChannel.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTServerCnx.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/broker/AdapterChannelTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/broker/MqttProxyAdapterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
Labels: no-need-doc

#609 Exclude grpc-related packages from pulsar-broker
  pom.xml
Labels: doc-info-missing

#605 Fix wrong behaviour when broker sends `DISCONNECT` message to proxy.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
Labels: no-need-doc

#613 Fix send `Disconnect` message many times from proxy to broker
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
Labels: no-need-doc

#615 Fix dynamic subscribe issue.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MessageAckTracker.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/AbstractCommonProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/AutoSubscribeHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
  mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/support/MessageAckTrackerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5IntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ProxyIntegrationTest.java
Labels: no-need-doc
