Repository streamnative/mop, pull requests merged in 2022-01, with the labels that each got.

#389 Use ``msg.release()`` to instead of `` ReferenceCountUtil.safeRelease(msg)``
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MessagePublishContext.java
Labels: type/cleanup

#392 Fix subscribe count exists dirty data issue
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
Labels: type/cleanup

#394 Use connection.send instead of channel.writeAndFlush.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/TopicSubscriptionManager.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
Labels: type/cleanup

#282 Add ci test report coverage and upload to codecov
  .github/workflows/pr_test.yml
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTTestBase.java
Labels: area/ci

#313 Speed up unit test
  .github/workflows/pr_test.yml
Labels: area/tests

#169 Add path-ignores to exclude files not trigger workflow
  .github/workflows/pr_test.yml
  .github/workflows/release-note.yml
Labels: area/ci

#397 Merge parallel ci test report (#396)
  .github/workflows/pr_test.yml
  pom.xml
Labels: area/ci

#402 Ci fix
  .github/workflows/pr_test.yml
Labels: area/ci

#404 Fix mip template
  .github/ISSUE_TEMPLATE/mip.md
Labels: area/documentation

#416 [MIP-1] Modify unreasonable variable names.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/handler/MopExceptionHelper.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/handler/MqttConnExceptionHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/handler/MqttExceptionHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/handler/package-info.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/DisconnectAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/PublishAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/SubscribeAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttDisconnectAckMessageHelper.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttPubAckMessageHelper.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttSubAckMessageHelper.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AbstractAckHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/MqttV5AckHandler.java
Labels: type/cleanup
