Repository streamnative/mop, pull requests merged in 2022-03, with the labels that each got.

#513 Fix many lookup request when use proxy.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
Labels: proxy, release/2.8.2, release/2.9.2, release/2.10.0

#525 Use ``BeanUtils#copyProperties`` to copy proxy config.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
  pom.xml
Labels: proxy, no-need-doc

#528 [Proxy] Support Proxy ``PUB-ACK``
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ClientReceiveMaximumTest.java
Labels: proxy, release/2.8.2, release/2.9.2, release/2.10.0, no-need-doc

#529 Fix MQTT proxy ``PUB-ACK`` topic with slash.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ClientReceiveMaximumTest.java
Labels: proxy, release/2.8.2, release/2.9.2, release/2.10.0, no-need-doc

#533 Check channel active state before send.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
Labels: no-need-doc

#532 Follow Apache Pulsar ``isAllowAutoTopicCreation`` configuration.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/ExceptionUtils.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5TestTopicAutoCreation.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5TestTopicAutoCreation.java
Labels: no-need-doc

#539 [Test] Add test to coverage topic unload and issue #538.
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
Labels: release/2.8.2, release/2.9.2, release/2.10.0, no-need-doc

#541 Support auto create topic affects by namespace policy.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5TestTopicAutoCreation.java
Labels: release/2.8.2, release/2.9.2, release/2.10.0, no-need-doc

#545 Fix duplicate subscribe issue.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTConnectionManager.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTSubscriptionManager.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AbstractAckHandler.java
  mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/MQTTSubscriptionManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ReasonCodeOnAllACKTest.java
Labels: release/2.8.2, release/2.9.2, release/2.10.0, no-need-doc

#554 Support NamespaceBundleOwnershipListener.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTNamespaceBundleOwnershipListener.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTTopicOwnershipListener.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
Labels: no-need-doc

#556 Remove the unused release workflow
  .github/workflows/release.yml
Labels: no-need-doc

#557 Fix incorrect client ID restriction behavior.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTConnectionManager.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/ConnectAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttConnectAckHelper.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AbstractAckHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AckHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/hivemq/base/MQTT3ReasonCodeTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/hivemq/proxy/MQTT3ProxyReasonCodeTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ReasonCodeOnAllACKTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ProxyReasonCodeAckTest.java
Labels: release/2.8.2, release/2.9.2, release/2.10.0, no-need-doc

#559 Revert "Fix incorrect client ID restriction behavior."
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTConnectionManager.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/ConnectAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttConnectAckHelper.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AbstractAckHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AckHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/hivemq/base/MQTT3ReasonCodeTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/hivemq/proxy/MQTT3ProxyReasonCodeTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ReasonCodeOnAllACKTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ProxyReasonCodeAckTest.java
Labels: no-need-doc

#560 Introduce system topic.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTConnectionManager.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/ActionType.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/ConnectEvent.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/DisabledSystemEventService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/EventListener.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/EventType.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/MQTTEventSystemTopicClient.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/MqttEvent.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/SourceEvent.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/SystemEventService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/SystemTopicBasedSystemEventService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/package-info.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/NettyUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/AuthorizationConfig.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/BasicAuthenticationConfig.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/TokenAuthenticationConfig.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/TLSTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/AuthorizationProxyTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/BasicAuthenticationProxyTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTLSTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/TokenAuthenticationProxyTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ServerReceiveMaximumTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5TestTopicAutoCreation.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5AuthorizationProxyReasonCodeOnAllAckTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ClientReceiveMaximumTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5SessionExpireIntervalTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5TestTopicAutoCreation.java
Labels: no-need-doc

#561 fix unsubscribe bug
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/TopicSubscriptionManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
Labels: no-need-doc

#564 Adjust the path of the package.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/DisableEventCenter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarEventCenter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarEventCenterImpl.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarEventListener.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarTopicChangeListener.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/package-info.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/ActionType.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/ConnectEvent.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/DisabledSystemEventService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/EventListener.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/EventType.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/MQTTEventSystemTopicClient.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/MqttEvent.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SourceEvent.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemEventService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/package-info.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/EventCenterTest.java
Labels: no-need-doc

#565 Support unique client id in MoP cluster.
  README.md
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTConnectionManager.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/MqttV5AckHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/ConnectEvent.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/DisabledSystemEventService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemEventService.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
Labels: doc-required

#567 [MIP-5] Support standalone dynamic regex subscription
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/DisableEventCenter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarTopicChangeListener.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/EventParserUtils.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5IntegrationTest.java
Labels: no-need-doc

#569 Support broker send disconnect message to client.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
Labels: no-need-doc
