Repository streamnative/mop, pull requests merged in 2023-07, with the labels that each got.

#1025 Remove grpc dependency
  mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTMetricsCollectorTest.java
  mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTMetricsProviderTest.java
  mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/ConfigurationUtilsTest.java
  mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/MqttMessageUtilsTest.java
  pom.xml
Labels: no-need-doc

#1024 Update README.md
  README.md
Labels: no-need-doc

#1030 Upgrade mqtt-codec 4.1.94
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
Labels: no-need-doc

#1031 Fix connection timeout ms
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/hivemq/base/CleanSessionTest.java
Labels: no-need-doc

#1032 Add Cache for event writer.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java
Labels: no-need-doc

#1033 Change log level to debug
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
Labels: no-need-doc

#1035 Support fast build docker image
  .ci/Dockerfile
  .github/workflows/dispatch-build-test-image.yaml
  pom.xml
Labels: doc-info-missing

#1037 Fix dispatch docker build
  .ci/Dockerfile
  .github/workflows/dispatch-build-test-image.yaml
Labels: no-need-doc, release/3.0, release/2.11, release/2.10.4

#1038 Bump project & pulsar version to 2.10.4.6
  mqtt-impl/pom.xml
  pom.xml
  tests/pom.xml
Labels: doc-info-missing, release/2.10.4

#1041 Fix `IllegalReferenceCountException` exception to break the callback
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/AdapterChannel.java
Labels: no-need-doc, release/3.0, release/2.11

#1040 Fix lookup issue for MQTT-5
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttPubAck.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ProxyIntegrationTest.java
Labels: no-need-doc

#1045 Fix NPE cased by inflating message
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonInboundHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/ProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
Labels: no-need-doc, release/3.0, release/2.11

#1050 Fix bundle is being unload IllegalState exception
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java
Labels: no-need-doc

#1049 Improve log to avoid too much error
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
Labels: no-need-doc

#1046 Fix NPE cased by inflating message
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonInboundHandler.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/ProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
Labels: no-need-doc, cherry-picked/branch-2.10, cherry-picked/branch-2.11, cherry-picked/branch-3.0

#1042 Fix IllegalReferenceCountException exception to break the callback
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/AdapterChannel.java
Labels: no-need-doc, cherry-picked/branch-2.10, cherry-picked/branch-2.11, cherry-picked/branch-3.0

#1051 Fix publish latency unit
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MessagePublishContext.java
Labels: no-need-doc

#1048 Fix mock object
  tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
Labels: no-need-doc

#1047 Add ping request for adapter channel
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
Labels: no-need-doc

#1054 Upgrade log4j2 version
  pom.xml
  tests/pom.xml
Labels: no-need-doc

#1053 Fix close reader NPE.
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java
Labels: no-need-doc

#1055 Revert "Add ping request for adapter channel (#1047)"
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
  mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
Labels: no-need-doc, cherry-picked/branch-2.11, cherry-picked/branch-3.0, cherry-picked/branch-2.10.4

#1059 Support MQTT performance testing tool
  .github/workflows/ci-publish.yaml
  .github/workflows/pr_test.yml
  mqtt-perf/.gitattributes
  mqtt-perf/.gitignore
  mqtt-perf/Dockerfile
  mqtt-perf/README
  mqtt-perf/banner.txt
  mqtt-perf/build.gradle
  mqtt-perf/build_perf.py
  mqtt-perf/config/checkstyle/checkstyle.xml
  mqtt-perf/gradle.properties
  mqtt-perf/gradle/wrapper/gradle-wrapper.jar
  mqtt-perf/gradle/wrapper/gradle-wrapper.properties
  mqtt-perf/gradlew
  mqtt-perf/gradlew.bat
  mqtt-perf/settings.gradle
  mqtt-perf/src/main/java/io/streamnative/mqtt/perf/CommandPerf.java
  mqtt-perf/src/main/java/io/streamnative/mqtt/perf/CommandPub.java
  mqtt-perf/src/main/java/io/streamnative/mqtt/perf/CommandSub.java
  mqtt-perf/src/main/java/io/streamnative/mqtt/perf/MqttPerf.java
  pom.xml
Labels: no-need-doc
